import operator as op
a=10;b=20
print("a & b are : ",a,b)
print()
print("a>=b: ",op.ge(a,b))
print()
print("a<=b: ",op.le(a,b))
print()
print("a==b: ",op.eq(a,b))
print()
print("a!=b: ",op.ne(a,b))
print()
print("a is b: ",a is b)
print()
print("a is not b: ",a is not b)
print()